### ISSUE TITLE
Multiplier for float

### ISSUE THREAD

**Issue by m-pauper** [brentp/echtvar#10]
As explained in the README:

> // for floats, upon annotation, the score is divided by multiplier and stored as an integer.
>            // higher values give better precision and worse compression.

And upon running Echtvar without specifying a multiplier

> [echtvar] warning! using a multiplier of 1 for float field PAT.
>      If this field contains values less than 1, use a multiplier so the values can be stored as integers.
>      Larger multipliers result in higher precision.

Could you please clarify what this means to help me determine what value to use as multiplier? Maybe using an example?

**Comment by m-pauper** [comment]
Yes, thanks a lot! 

Thus, in this example if I do not want to lose any information I would multiply with 10^6? 
This would worsen compression impacting the output size, but does it also impact `encode` and `annotate` speed?

**Comment by brentp** [comment]
That's basically it. It will affect the speed in-so-much as the (compressed) size will be larger and therefore take longer to read from disk and longer to decompress, but I doubt it will be noticeable unless you are measuring time very carefully.
