### ISSUE TITLE
Multi-allelic sites

### ISSUE THREAD

**Issue by m-pauper** [brentp/echtvar#11]
Hello,

I have tried using Echtvar to annotate with some genome-wide scores such as CADD or [regBase](https://github.com/mulinlab/regBase). These have a score for all possible variants in the genome, so for each position there is one REF and 3 ALT alleles. If the 3 ALT alleles are collapsed in one VCF record in the _annotation_ file, then Echtvar will only annotate variants from _query_ file if it matches the **first** of the 3 alleles.

Example of collapsed variant:
`22      16055959        .       G       A,C,T   .       .       REG=0.11765,0.0974135,0.134254;`

In this case, Echtvar would only annotate G>A variants. G>C or G>T will get missing value.

**Comment by brentp** [comment]
yes, you'll have to decompose the VCF first. 
I'll make this an error so you don't build without knowing. 
Thanks for continuing to report these usability issues.

**Comment by brentp** [comment]
exactly, all VCFs seen by echtvar should be decomposed and normalized. I will update the README with this and add checks.

**Comment by brentp** [comment]
I'll open this till I commit the fix.
