### ISSUE TITLE
Encode TSV indexed files

### ISSUE THREAD

**Issue by edg1983** [brentp/echtvar#14]
Hello Brent,

Great tool as usual!

I'm wondering if it's possible to encode also TSV indexed files or you have plan for this? 
This would be useful to annotate impact prediction scores with single base resolution, like CADD, which are huge and provided as TSV and not VCF. Of course one can convert them to VCF and then encode them, but it would be convenient if we can encode them directly.

Thanks!

**Comment by brentp** [comment]
Hi Edoardo, 
I probably won't support that directly (unless someone funds that development). It's simple enough to convert TSV to VCF and echtvar encode  can accept STDIN, so you never even need to write the VCF to disk.
I have a script to do this for any/all of dbsnfp [here](https://github.com/brentp/echtvar/blob/main/scripts/dbnsfp.py) and I'm happy to guide with any problems you encounter should you try it.

**Comment by edg1983** [comment]
Thanks Brent! 
I will go ahead using TSV -> VCF conversion and then pipe to echtvar encode as suggested
