### ISSUE TITLE
Running on MacOS

### ISSUE THREAD

**Issue by sstadick** [brentp/echtvar#17]
Before I go down the rabbit hole of getting this to run on my Mac, is there a known reason why it doesn't work? It will compile with `cargo build --target x86_64-apple-darwin` but seg faults when I try to produce an encoding. I don't see any obvious reason whey it shouldn't work based on the `Cargo.toml`.

I'm interested in getting this working if there is no fundamental blocker.

**Comment by brentp** [comment]
Hi Seth, I'm glad to have another pair of eyes on this!
I really don't know would guess it's something with:
```
stream-vbyte = {version = "0.4.0", features=["x86_ssse3", "x86_sse41"]}
```
In which case, you could try replacing, for example:
```
use stream_vbyte::{encode::encode, x86::Sse41};
```
with:

```
use stream_vbyte::{encode::encode,     scalar::Scalar};
```
(and then update the `encode`)

Another place to look might be
```
zip = { version = "0.5", default-features = false, features=["deflate"] }
```
but I assume that deflate is fine on OSX (?).

And finally, I just **cargo**-culted [this](https://github.com/brentp/echtvar/blob/main/rust-toolchain.toml) but I don't know if that affects other platforms.

**Comment by brentp** [comment]
Oh, and the [.cargo/config](https://github.com/brentp/echtvar/blob/main/.cargo/config) might be causing problems.

**Comment by sstadick** [comment]
https://github.com/brentp/echtvar/pull/18

**Comment by sstadick** [comment]
It was a little bit of everything! I don't have an Ubuntu machine handy to verify that I didn't make local development on linux harder, but that would be worth a check.
