### ISSUE TITLE
INFO field header key order

### ISSUE THREAD

**Issue by JakeHagen** [brentp/echtvar#19]
Hi Brent

echtvar annotates the header with this line
```
"##INFO=<ID={},Type={},Number=1,Description=\"{}\">",
```

I think this is fine, as I could not find anything in the VCF spec about key ordering, but in your vcfgo, the regex that checks the header doesn't match the ordering from ecthvar, which causes an error when using vcfgo to parse echtvar vcfs.

```
var typeRe = `String|Integer|Float|Flag|Character|Unknown`
var infoRegexp = regexp.MustCompile(fmt.Sprintf(`##INFO=<ID=(.+),Number=([\dAGR\.]*),Type=(%s),Description="(.*)">`, typeRe))
```

Can we make a change to one of these codebases? If so, which one? I am happy to submit a pull request, unless its easier for you to make these small changes yourself.

**Comment by brentp** [comment]
wow. I am surprised that no one has hit this before in vcfgo. I'd definitely accept a PR to fix it there. Thanks for diagnosing!

**Comment by brentp** [comment]
I can also simply change the order in echtvar if it ends up being a PITA to get the correct regex stuff in vcfgo.

**Comment by JakeHagen** [comment]
I think I almost have the correct regex but I would appreciate also changing the ordering in echtvar. Thank you!
