### ISSUE TITLE
dbsnp and multiallelic VCFs

### ISSUE THREAD

**Issue by sstadick** [brentp/echtvar#20]
In the docs I noticed there is mention of a [dbsnp](https://github.com/brentp/echtvar#annotate) zip file that was created at some point? How did you go about decomposing the dbsnp VCF? I am trying to avoid yet another custom tool to decompose the fields in a sensible way so that I can use it with echtvar.

**Comment by brentp** [comment]
I didn't actually create a dbsnp zip file, just used it as an example. If I were to create one, I'd use bcftools norm for the decomposition. 

If you mean decomposing the bit field that's stored as a string, then you'll have to write your own for that. :vomiting_face:

**Comment by sstadick** [comment]
Unless I'm using the wrong set of options on `bcftools` it doesn't decompose the INFO fields. So extracting the `CAF` from the dbsnp vcf to use with echtvar is only moderately useful :(

**Comment by brentp** [comment]
it will decompose them if Number=A or Number=R, but if it has Number=. then it will not.

**Comment by sstadick** [comment]
🤯 I must have been unlucky every time I've cared about decomposing multiallelics with bcftools norm. Time to go digging in dbsnp to see why the CAF field is `.` and not `R`. 

Thank you!
