### ISSUE TITLE
warn for VCFv4.2:[warning] found non ACGT ALT character '*', encoding as 'T' for position: 774922

### ISSUE THREAD

**Issue by liserjrqlxue** [brentp/echtvar#22]
In VCFv4.2, the ‘\*’ allele is reserved to indicate that the allele is missing due to a upstream deletion.
Then each deletion variant will emit some ’\*‘ alleles.
`Echtvar` will warning for **each** '*' allele like:`[warning] found non ACGT ALT character '*', encoding as 'T' for position: 774922`.
In a `wgs` example, I got 11099 lines of `[warning]`, this is annoying.
Can `echtvar` ignore this type of warn or should I remove '\*' alleles before?

**Comment by brentp** [comment]
Yes, this is annoying. I will have it report only the first $n occurrences of this error.

**Comment by brentp** [comment]
Hi, can you test this binary?
[echtvar.gz](https://github.com/brentp/echtvar/files/8878372/echtvar.gz)

It should report the warning only 10 times.

**Comment by liserjrqlxue** [comment]
Yes, in my test only output 10 times.
*BUT* it seems cost 50% more compute resources.
This may be caused by other update like ‘order vcf INFO'

**echtvar 0.1.5 in release**
```
[echtvar] evaluated 5012080 variants (159417 / second). wrote 5012080 variants.
        Command being timed: "echtvar anno -e ../echtvar/gnomad.exomes.r2.1.1.echtvar.zip output/input.norm.vcf.gz test.echtvar.bcf"
        User time (seconds): 48.06
        System time (seconds): 2.17
        Percent of CPU this job got: 153%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:32.63
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 20968
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 5577
        Voluntary context switches: 69652
        Involuntary context switches: 8684
        Swaps: 0
        File system inputs: 547792
        File system outputs: 436408
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**echtvar 0.1.6 in attachment**
```
[echtvar] evaluated 5012080 variants (92376 / second). wrote 5012080 variants.
        Command being timed: "./echtvar anno -e ../echtvar/gnomad.exomes.r2.1.1.echtvar.zip output/input.norm.vcf.gz test.echtvar.bcf"
        User time (seconds): 71.79
        System time (seconds): 4.58
        Percent of CPU this job got: 139%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:54.81
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 23576
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1186178
        Voluntary context switches: 70217
        Involuntary context switches: 7113
        Swaps: 0
        File system inputs: 0
        File system outputs: 434608
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by brentp** [comment]
Hi, thanks for noting this. I uploaded the dev binary built using musl. Here is the linux one. It's actually a bit faster than 0.1.5 release on my quick test.
[echtvar.gz](https://github.com/brentp/echtvar/files/8888812/echtvar.gz)
I'll make a release this week.

**Comment by liserjrqlxue** [comment]
BTW, I can't `cargo build` with `error`:
```
error: cannot produce proc-macro for `c2rust-bitfields-derive v0.2.1` as the target `x86_64-unknown-linux-gnu` does not support these crate types
```

This is not a big deal since your high frequency release.

**Comment by liserjrqlxue** [comment]
I used raw command `cargo build`.
With `cargo build --release --target x86_64-unknown-linux-gnu`, also error as:
```
   Compiling stream-vbyte v0.4.0
   Compiling form_urlencoded v1.0.1
   Compiling pest v2.1.3
   Compiling serde_json v1.0.81
   Compiling textwrap v0.9.0
   Compiling libc v0.2.126
   Compiling proc-macro2 v1.0.39
   Compiling memchr v2.5.0
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/wangyaoshen/.cargo/registry/src/github.com-1ecc6299db9ec823/stream-vbyte-0.4.0/src/lib.rs:113:13
    |
113 |     feature(portable_simd)
    |             ^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `stream-vbyte` due to previous error
warning: build failed, waiting for other jobs to finish...
```

<img width="900" alt="image" src="https://user-images.githubusercontent.com/5977521/173487200-abc9984a-bdf3-451a-92d8-bf6868f3aef6.png">

I'm using 'rust' installed from `yum`, I'll test `rustup`.

**Comment by liserjrqlxue** [comment]
After reinstall `rust` from `rustup`. I can `cargo build --release --target x86_64-unknown-linux-gnu` with `nightly` release.
Then I got stuck in `libz-sys v1.1.8`:
1. `CMake 3.5.1 or higher is required`[solved]
2. `/usr/bin/ld: cannot find -lc`
rustflags = ["-C", "target-feature=+crt-static"]

I go back `cargo build`, After comment out `rustflags = ["-C", "target-feature=+crt-static"]` base on https://github.com/brentp/echtvar/pull/18#issuecomment-1082204197, I got a **non-static** `echtvar` binary with size of 57M.

**Comment by liserjrqlxue** [comment]
Above builds use `CentOS Linux release 7.9.2009 (Core)` with `glibc 2.17`.
With my wsl `Ubuntu 20.04.4 LTS` with `glibc 2.31`, `cargo build --release --target x86_64-unknown-linux-gnu` got a 9.5M static `echtvar` binary. 😄

**Comment by brentp** [comment]
OK. Great! Thanks for reporting. I'll make a new release.
