### ISSUE TITLE
Help message for echtvar anno should call the arg <OUTPUT_BCF>, not <OUTPUT_VCF>

### ISSUE THREAD

**Issue by dvg-p4** [brentp/echtvar#29]
One last incredibly small nitpick. Unless there's an option to output uncompressed vcf that I'm not seeing?

**Comment by brentp** [comment]
if the -o argument ends with "bcf" it will write bcf, otherwise, it will write compressed vcf. 
For now, you can use " -o /dev/stdout" and pipe to zcat. If you insist, I can probably expose an argument to modify this.

**Comment by brentp** [comment]
I pushed a fix for this so when you run `echtvar anno -h` it now shows:
```
...
ARGS:
    <INPUT_VCF>     input vcf or bcf
    <OUTPUT_VCF>    path to bcf/vcf.gz output file (determined by extension)
```

**Comment by dvg-p4** [comment]
Ah gotcha! I was trying to output to `out.vcf` and getting a file that wasn't readable by `less` but was by `bcftools`--so I assumed it was a `bcf`. But if it was actually a gzipped vcf, that would also lead to the observed binary-ness
