### ISSUE TITLE
error om encoding dbsnp - "Large file option has not been set". echtvar 0.1.7

### ISSUE THREAD

**Issue by ruslan-abasov** [brentp/echtvar#30]
>./echtvar encode dbsnp.echtvar.zip dnsnp.etchvar.json dnsnp.vcf.gz
>[echtvar] adding VCF:/data1/mnt/LMBALL/RefData_VMP01/annotation/variation/dbsnp/156/hg38/ready.vcf.gz
>[echtvar] on chromosome "1"
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 1612563
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 4522956
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 4522956
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 10012946
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 11544538
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 12854354
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 15827828
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 15974201
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 15974201
>[warning] found non ACGT ALT character 'N', encoding as 'T' for (1-based) position: 16062393
>[echtvar] on chromosome "2"
>[echtvar] on chromosome "3"
>[echtvar] on chromosome "4"
>[echtvar] on chromosome "5"
>[echtvar] on chromosome "6"
>[echtvar] on chromosome "7"
>[echtvar] on chromosome "8"
>[echtvar] on chromosome "9"
>[echtvar] on chromosome "10"
>[echtvar] on chromosome "11"
>[echtvar] on chromosome "12"
>[echtvar] on chromosome "13"
>[echtvar] on chromosome "14"
>[echtvar] on chromosome "15"
>[echtvar] on chromosome "16"
>[echtvar] on chromosome "17"
>[echtvar] on chromosome "18"
>[echtvar] on chromosome "19"
>[echtvar] on chromosome "20"
>[echtvar] on chromosome "21"
>[echtvar] on chromosome "22"
>[echtvar] on chromosome "X"
>[echtvar] on chromosome "Y"
>[echtvar] on chromosome "M"
>[echtvar] found 1096965712 unique values for dbsnpid)
>thread 'main' panicked at 'error writing to zip file: Custom { kind: Other, error: "Large file option has not been set" }', >src/commands/encoder_cmd.rs:462:31
>note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by brentp** [comment]
hmm. thanks for reporting.
I do have large file set on the entire archive, but here, I update to include on each individual file as well. Would you try this binary and let me know if it works? Just gunzip, chmod +x and run as ./echtvar_dev ...

[Uploading echtvar_dev.gz…]()

**Comment by ruslan-abasov** [comment]
Thanks! Works great!

**Comment by brentp** [comment]
thanks for following up. I pushed a new release with this fix and other small changes:
https://github.com/brentp/echtvar/releases/tag/v0.1.8
