### ISSUE TITLE
🐛 non ACGT ALT character

### ISSUE THREAD

**Issue by migbro** [brentp/echtvar#36]
We were using echtvar to annotate an output from a GATK germline workflow, in which they have the occasional `*` alt from when the input was multi-allelic (as far as I know, it signifies that another upstream variant encompasses this position as well as the variant at the is position). When you break it up, it becomes a singular ref to `*` call, for example:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1    1048544 .       A       *       1       PASS    AC=1
```
During annotation you get this warning:
`[warning] found non ACGT ALT character '*', encoding as 'T' for (1-based) position: 10485441`

Which makes sense, but if your annotation file does have a ref to `T` call at that position, then the `*` ends up getting an annotation intended for a real alt `T`. So if the annotation file has:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	1048544	.	A	T	1	PASS	val0=1867825;nvar=0;AC=1;str=YES
```
echtvar will annotation that `*` alt as:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	1048544	.	A	*	1	PASS	AC=1;aval=1867825;external_AC=1
```

We believe this to be a bug. We can work on a fix, but if you have a suggestion off the top of your head, like "remedy by changing x to y in this source code" or "I'd just toss all `*` variants after splitting multi-allelics for reason x", we'd be very appreciative. Thanks again in advance!

**Comment by brentp** [comment]
I think a good alternative is to just skip these. so they don't get encoded in the echtvar archive.
What do you think? 
I can make this an option from the command-line, but I don't like to add options that will never be used and only add surface area for confusion.

**Comment by brentp** [comment]
You can experiment with this by looking at the `var32::encode` call on line 397 in `src/commands/encoder_cmd.rs`.
Perhaps `var32::encode` should return a `Result<u32,AlleleError>`. I am happy to do this after a bit of brainstorming.

oh, and thanks for reporting!

**Comment by brentp** [comment]
another option is that variants with '*' ALT could be encoded somehow as long variants. I'd have to see if this can be done without performance costs as it would be an extra check in an important code path.

**Comment by migbro** [comment]
Hmmm, I can't quite tell when certain things happen. Like, the file being used to annotate the input vcf obviously does not have `*`, but the input vcf does When it hits that step of annotating the allele, I think an appropriate response might be a warning, something like `* is an invalid allele for annotation. Skipping and outputting original entry`. Alternatively, maybe when I play with the code some more I'll know, it can be encoded as `N` and it'd still get skipped. It seems unlikely that any annotation reference would purposely assign `INFO` to an `N1`, but crazy things happen...

**Comment by brentp** [comment]
I pushed a fix for that. Not sure how my tests passed locally.

**Comment by migbro** [comment]
Hi @brentp thanks for merging our changes! Are you planning on creating a release that encapsulates everything? Just asking so that when we build our docker with the updated software, we'll know whether we can use a release, or just point to a commit to lock it in to ensure reproducibility. Thanks again for addressing our issues and your quick response!

**Comment by brentp** [comment]
Thanks for reporting and fixing!!!
Yes, I'll make a release this week. Probably tomorrow.
Let me know if you have any other problems.

**Comment by brentp** [comment]
just pushed a release for this: https://github.com/brentp/echtvar/releases/tag/v0.2.0
thanks very much!

**Comment by migbro** [comment]
Great! Thanks to you too!
