### ISSUE TITLE
Unsupported Field Type: Flag

### ISSUE THREAD

**Issue by Fyodir** [brentp/echtvar#41]
When creating echtvar .zip files using `echtvar encode`. Echtvar encode appears to be unable to accept INFO segments with the "Type=Flag" parameter. This occurs when trying to convert gnomad VCF files for use in annotation.

echtvar zip files build successfully for INFO segments with String/Integer types.

## Error Message
```
thread 'main' panicked at '[echtvar] unsupported field type: Flag for field lcr', src/commands/encoder_cmd.rs:216:18                                                                                                                                    
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```

## conf.json
```
[
        ...
        {
                "field": "lcr", 
                "alias": "gnomad4_lcr",
        },
        ...
]
```

## CMD
```
echtvar encode gnomad_v4-0_chrY.echtvar.zip config.json gnomad.genomes.v4.0.sites.chrY.vcf.gz
```

**Comment by brentp** [comment]
yes, this is correct, `echtvar` doesn't currently support encoding `Flag` fields.
