### ISSUE TITLE
Missing Number= with gnomad.v3.1.2.echtvar.v2.zip

### ISSUE THREAD

**Issue by fellen31** [brentp/echtvar#43]
Hi, 

Thanks for providing gnomad.v3.1.2.echtvar.v2.zip. However, I'm having trouble with some downstream tools that complain about the INFO line of the annotated VCF, where there's no number in the INFO lines. 

Command run: 

```
echtvar anno -e gnomad.v3.1.2.echtvar.v2.zip -e CoLoRSdb.GRCh38.v1.0.0.deepvariant.glnexus.zip 7.bed.bcf 7.bed_echtvar_anno.bcf.gz
```

Missing `Number=number`

```
##INFO=<ID=gnomad_ac,Number=,Type=Integer,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_an,Number=,Type=Integer,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_nhomalt,Number=,Type=Integer,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_af,Number=,Type=Float,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_popmax_ac,Number=,Type=Integer,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_popmax_an,Number=,Type=Integer,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_popmax_nhomalt,Number=,Type=Integer,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_popmax_af,Number=,Type=Float,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_controls_and_biobanks_af,Number=,Type=Float,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_controls_and_biobanks_nhomalt,Number=,Type=Integer,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
##INFO=<ID=gnomad_filter,Number=,Type=String,Description="added by echtvar from gnomad.v3.1.2.echtvar.v2.zip">
```

This is not the case for a database I have encoded myself:
```
##INFO=<ID=colorsdb_af,Number=1,Type=Float,Description="added by echtvar Allele Frequency estimate for each alternate allele">
##INFO=<ID=colorsdb_ac,Number=1,Type=Integer,Description="added by echtvar Allele count in genotypes">
```

Any idea what is up with gnomad.v3.1.2.echtvar.v2.zip?

PS, Seems to have sneaked in a `None` here as well:
```
##echtvar_annoCommand=anno -i None 20.bed.bcf 20.bed_echtvar_anno.bcf.gz -e "gnomad.v3.1.2.echtvar.v2.zip -e CoLoRSdb.GRCh38.v1.0.0.deepvariant.glnexus.zip"
```

**Comment by brentp** [comment]
hi, sorry for the delay, can you show the json file that you used to create the problematic zip file?

**Comment by fellen31** [comment]
Hi, no worries. The problematic zip file seems to be the pre-made file for hg38 provided with the releases. 

I could remake the file using your json (https://github.com/brentp/echtvar/blob/main/examples/gnomad.v3.1.2.json) and use the resulting file without problems. Is the file provided under releases perhaps using an older version of echtvar?

**Comment by brentp** [comment]
hi, my reply seems to have been lost...
so you're saying it works if you remake with a recent version of echtvar?
If so, I'll see if I can get a new version of the zips uploaded somewhere.

**Comment by fellen31** [comment]
> hi, my reply seems to have been lost... so you're saying it works if you remake with a recent version of echtvar? If so, I'll see if I can get a new version of the zips uploaded somewhere.

Yes! It seems like the later version of echtvar produces a valid VCF. Would be great!

**Comment by fellen31** [comment]
Thanks! 🙌
