### ISSUE TITLE
error when encoding gnomad 4.1 vcf

### ISSUE THREAD

**Issue by atimms** [brentp/echtvar#44]
I'm trying to create an archive from gnomad 4.1 VCF using the command.

./echtvar \
   encode \
   ${gnomad_zip} \
   ${conf_json} \
   ${gnomad_vcf} 

with the json being:
[{"field": "AF", "alias": "gnomad_af", multiplier: 2000000}]

But I'm getting the error message:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/commands/encoder_cmd.rs:249:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Thanks for any help.

Andrew

**Comment by brentp** [comment]
hi, this means you don't have write permission to wherever you are trying to create `${gnomad_zip}`

**Comment by atimms** [comment]
Thanks for the swift response, it was an oversight on my part. 

Thanks for writing another super useful tool!!
